FROM ubuntu:24.04

RUN apt update
RUN apt install -y python3 python3-pip
RUN pip install --break-system-packages requests

COPY FlClashCore /tmp/FlClashCore
COPY helper /root/helper
COPY entrypoint.sh /root/entrypoint.sh

RUN chsh -s /bin/bash nobody && usermod -d /tmp nobody

CMD ["/bin/bash", "/root/entrypoint.sh"]