FROM ubuntu:24.04

RUN apt update
RUN apt install -y python3 python3-pip
RUN pip install --break-system-packages requests

COPY FlClashCore /root/secure/FlClashCore
COPY helper_fixed /root/helper_fixed
COPY entrypoint_fixed.sh /root/entrypoint_fixed.sh

RUN chsh -s /bin/bash nobody && usermod -d /tmp nobody

CMD ["/bin/bash", "/root/entrypoint_fixed.sh"]